import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
          <title>Navigation bar using next js and tailwind css</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </div>
  )
}
